### ISSUE TITLE
项目申请：tao Go语言实现的网络编程框架

### ISSUE THREAD

**Issue by leesper** [hyper0x/awesome-go-China#25]
项目地址：https://github.com/leesper/tao
目前479颗STAR，被fork110次，Go语言实现的网络编程框架，写有详细的实现思路文档，放在简书上，地址为：https://www.jianshu.com/p/c322edca985f
请求加入项目列表，献丑了～

**Comment by hyper0x** [comment]
Done.

**Comment by leesper** [comment]
谢谢您！
