### ISSUE TITLE
申请添加go-etl项目

### ISSUE THREAD

**Issue by Breeze0806** [hyper0x/awesome-go-China#52]
[go-et](https://github.com/Breeze0806/go-etl)是一个类似阿里datax可以进行异构数据源相互离线数据迁移的项目，但是我不知道这个可不可以加入列表中，并且应该加入到哪个分类中？

**Comment by hyper0x** [comment]
Hi，我添加了一个“DataSource”的分类，你可以加到那里面，fork & pr 就可以。

**Comment by Breeze0806** [comment]
感谢大佬的回复，您开的课真的很棒，不仅让我有很好的学习体验，而且使我有了做好一个开源项目的想法。

**Comment by hyper0x** [comment]
> 感谢大佬的回复，您开的课真的很棒，不仅让我有很好的学习体验，而且使我有了做好一个开源项目的想法。

赞👍，对你有帮助就好🙂
